[rlbot]
launcher = "custom"
launcher_arg = "legendary"

[match]
game_mode = "Soccer"
game_map_upk = "Stadium_P"

[mutators]
match_length = "TenMinutes"

[[cars]]
name = "Boomer"
type = "psyonix"
skill = "allstar"

[[cars]]
config = "bot.toml"
team = 1

[[cars]]
config = "phantom/../bot.toml"
team = "blue"
loadout_file = "phantom/../loadout.toml"
